module.exports'),
    ...require('./adapters/JSONFileSync.js'),
        ...require('./adapters/LocalStorage.js'),
            ...require('./adapters/LocalStorage.js'),
                ...require('./adapterrySync.js'),
                    ...require('./adapters/TextFync.js')
                        ...require('.//Lot.js'),
                           ileSREQUIRS")./LowSync.js'),
                           }Low.js'),
                               ...require('./LowSync.js'),
                               }Low.js'),
                                   ...require('./LowSync.js'),
                                   }
